### ISSUE TITLE
Failed to sign in by cn

### ISSUE THREAD

**Issue by ffffatgoose** [sosconf/Account-Authentication-Service#9]
Unable to sign in like this:
![image](https://user-images.githubusercontent.com/44337029/65369158-7811d200-dc7c-11e9-95ed-4a77d0c5a11e.png)
After some test, I find some thing wrong with the OPENLDAP……
![image](https://user-images.githubusercontent.com/44337029/65369152-64ff0200-dc7c-11e9-8452-23ecacaf194b.png)
Ask for hint :)

**Comment by Hephaest** [comment]
@ffffatgoose 
I see... this problem is caused by OpenLDAP status rather than password error. Please check out whether you have enabled SELinux without adding LDAP write and read access.

**Comment by ffffatgoose** [comment]
I found an answer to the similar problem **Unable to bind to server: Can't contact LDAP server** :
[https://stackoverflow.com/questions/23490848/ldap-bind-unable-to-bind-to-server-cant-contact-ldap-server](url)
The reason why it is unable to contact LDAP server is that SELinux is running enforced. On the other hand, SELinux doesn't allow your httpd daemon to talk to the LDAP server on the same machine. So SELinux disallow the LDAP connection, even though ldaps is enabled in firewalld. 
I checked the SELinux configuration of httpd using and found the anon is off……:
```
# getsebool -a | grep httpd
httpd_anon_write --> off
httpd_builtin_scripting --> on
httpd_can_check_spam --> off
httpd_can_connect_ftp --> off
httpd_can_connect_ldap --> off
httpd_can_connect_mythtv --> off
httpd_can_connect_zabbix --> off
httpd_can_network_connect --> off
httpd_can_network_connect_cobbler --> off
httpd_can_network_connect_db --> off
```
So enable the SELinux network connectivity is sure to solve my problem, besides it's no need to restart the Apache. Below is the command to turn on the connectivity:
`setsebool -P httpd_can_network_connect on`
